[package]
name = "virtchk"
version = "0.1.1"
edition = "2024"

[profile.dev]
panic = "abort"
debug = "full"

[profile.release]
panic = "abort"

[target.'cfg(windows)'.dependencies.windows-sys]
version = "0.61.0"
features = ["Win32_System_Console","Win32_System_Threading","Win32_System_Kernel","Win32_System_WindowsProgramming","Win32_System_SystemServices","Win32_System_Diagnostics_Debug","Win32_System_SystemInformation","Win32_System_LibraryLoader","Win32_System_Hypervisor"]

[target.'cfg(unix)'.dependencies.libc]
version = "0.2.175"
default-features = false

[dependencies]
static-collections = "0.1.2"
